# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPHODW39oyJqMIqEkt0qrUaFijFqbZdJ
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go


# =====================
# CONFIGURAÇÃO DA PÁGINA
# =====================
st.set_page_config(layout="wide")

st.markdown("""
<h1 style='margin-bottom:0;'>Performance de Anúncios</h1>
<h4 style='color:#6c757d; margin-top:5px;'>Corretor Gramado & Canela</h4>
<hr>
""", unsafe_allow_html=True)

# =====================
# ESTADO DA APLICAÇÃO
# =====================
if "visao" not in st.session_state:
    st.session_state.visao = None

# =====================
# UPLOAD DO ARQUIVO
# =====================
uploaded_file = st.file_uploader("📤 Upload do Excel", type=["xlsx"])

if uploaded_file is None:
    st.info("⬆ Envie o arquivo Excel para começar")
    st.stop()

# =====================
# LEITURA DO EXCEL
# =====================
df = pd.read_excel(uploaded_file)

# =====================
# VALIDAÇÃO MÍNIMA
# =====================
colunas_esperadas = [
    'CEP',
    'Criação',
    'Última atualização',
    'Total de visualizações',
    'Total de contatos',
    'Tipo do anúncio'
]

for c in colunas_esperadas:
    if c not in df.columns:
        st.error(f"Coluna faltando: {c}")
        st.stop()

# =====================
# TRATAMENTO DE DADOS
# =====================
df['CEP'] = df['CEP'].astype(str).str.zfill(8)
df['Criação'] = pd.to_datetime(df['Criação'], errors='coerce', dayfirst=True)
df['Última atualização'] = pd.to_datetime(df['Última atualização'], errors='coerce', dayfirst=True)

df['taxa_conversão'] = np.where(
    df['Total de visualizações'] > 0,
    (df['Total de contatos'] / df['Total de visualizações']) * 100,
    0
)

# =====================
# GAUGE — TAXA DE CONVERSÃO GERAL (RÁPIDO)
# =====================
total_visualizacoes = df['Total de visualizações'].sum()
total_contatos = df['Total de contatos'].sum()

taxa_conversao_geral = (
    (total_contatos / total_visualizacoes) * 100
    if total_visualizacoes > 0 else 0
)

fig_gauge = go.Figure(go.Indicator(
    mode="gauge+number",
    value=taxa_conversao_geral,
    number={"suffix": "%", "valueformat": ".2f"},
    title={"text": "Taxa de Conversão Geral"},
    gauge={
        "axis": {"range": [0, 2]},
        "bar": {"color": "black"},  # barra neutra leve
        "steps": [
            {"range": [0, 0.8], "color": "#dc3545"},
            {"range": [0.8, 1.5], "color": "#ffc107"},
            {"range": [1.5, 2.0], "color": "#198754"},
        ],
        "threshold": {
            "line": {"color": "black", "width": 5},
            "thickness": 0.85,
            "value": taxa_conversao_geral
        }
    }
))

st.plotly_chart(fig_gauge, use_container_width=True)


# =====================
# BASE GLOBAL
# =====================
base = df.copy()

# =====================
# KPIs PRINCIPAIS
# =====================
total_visualizacoes = base['Total de visualizações'].sum()
total_contatos = base['Total de contatos'].sum()
aluguel = base['Valor do aluguel'].count()

m1, k1, k2, k3, k4, m2 = st.columns([2, 2, 2, 2, 2, 1])

k1.metric("Visualizações", f"{total_visualizacoes:,}".replace(",", "."))
k2.metric("Contatos", f"{total_contatos:,}".replace(",", "."))
k3.metric("Anúncios Ativos", len(base))
k4.metric("Aluguéis", f"{aluguel:,}".replace(",", "."))

# =====================
# SEGMENTAÇÃO
# =====================
premium = base[base['Tipo do anúncio'] == 'Destaque Premium']
destaque = base[base['Tipo do anúncio'] == 'Destaque']
padrao = base[base['Tipo do anúncio'] == 'Padrão']

padrao_super = padrao[padrao['taxa_conversão'] >= 10]
padrao_destaque = padrao[(padrao['taxa_conversão'] >= 3) & (padrao['taxa_conversão'] < 10)]
padrao_geral = padrao[padrao['taxa_conversão'] < 3]

# =====================
# FUNÇÃO DE CARD (SAFE)
# =====================
def card(label, value, key, icon="📦"):
    with st.container(border=True):
        st.markdown(
            f"""
            <div style="text-align:center;">
                <div style="font-size:28px;">{icon}</div>
                <div style="font-size:14px; color:#6c757d;">{label}</div>
                <div style="font-size:32px; font-weight:700;">{value}</div>
            </div>
            """,
            unsafe_allow_html=True
        )
        return st.button("Ver detalhes", key=key, use_container_width=True)

# =====================
# DESTAQUE PREMIUM
# =====================
st.subheader("Anúncios — Destaque Premium")
p1, p2, p3 = st.columns(3)

with p1:
    if card("Todos os Anúncios", len(premium), "premium_total"):
        st.session_state.visao = "premium_total"

with p2:
    if card("Receberam Mensagem", len(premium[premium['Total de contatos'] > 0]), "premium_com", "✅"):
        st.session_state.visao = "premium_com"

with p3:
    if card("Não Receberam Mensagem", len(premium[premium['Total de contatos'] == 0]), "premium_sem", "❌"):
        st.session_state.visao = "premium_sem"

# =====================
# DESTAQUE
# =====================
st.subheader("Anúncios — Destaque")
d1, d2, d3 = st.columns(3)

with d1:
    if card("Todos os Anúncios", len(destaque), "destaque_total"):
        st.session_state.visao = "destaque_total"

with d2:
    if card("Receberam Mensagem", len(destaque[destaque['Total de contatos'] > 0]), "destaque_com", "✅"):
        st.session_state.visao = "destaque_com"

with d3:
    if card("Não Receberam Mensagem", len(destaque[destaque['Total de contatos'] == 0]), "destaque_sem", "❌"):
        st.session_state.visao = "destaque_sem"

# =====================
# PADRÃO — GERAL
# =====================
st.subheader("Anúncios — Padrão (Geral)")
g1, g2, g3 = st.columns(3)

with g1:
    if card("Todos os Anúncios", len(padrao_geral), "padrao_total"):
        st.session_state.visao = "padrao_total"

with g2:
    if card("Receberam Mensagem", len(padrao_geral[padrao_geral['Total de contatos'] > 0]), "padrao_com", "✅"):
        st.session_state.visao = "padrao_com"

with g3:
    if card("Não Receberam Mensagem", len(padrao_geral[padrao_geral['Total de contatos'] == 0]), "padrao_sem", "❌"):
        st.session_state.visao = "padrao_sem"

# =====================
# PADRÃO — DESTAQUES
# =====================

r1, r2 = st.columns(2)

with r1:
    if card("Converteram mais de 10% das visualizações", len(padrao_super), "padrao_super", "🔥"):
        st.session_state.visao = "padrao_super"

with r2:
    if card("Converteram entre 3% e 10% das visualizações", len(padrao_destaque), "padrao_destaque", "📈"):
        st.session_state.visao = "padrao_destaque"

st.divider()

# =====================
# EXIBIÇÃO DA TABELA
# =====================

def estilo_taxa_conversao(val):
    if val < 0.6:
        return "color: red; font-weight: bold;"
    elif 0.6 <= val <= 1:
        return "color: orange; font-weight: bold;"
    else:
        return "color: green; font-weight: bold;"


def estilo_visualizacoes(val, tipo):
    limites = {
        "Destaque Premium": 300,
        "Destaque": 200,
        "Padrão": 100
    }
    limite = limites.get(tipo, 0)
    if val < limite:
        return "color: red; font-weight: bold;"
    else:
        return "color: orange; font-weight: bold;"


mapa = {
    "premium_total": premium,
    "premium_com": premium[premium['Total de contatos'] > 0],
    "premium_sem": premium[premium['Total de contatos'] == 0],

    "destaque_total": destaque,
    "destaque_com": destaque[destaque['Total de contatos'] > 0],
    "destaque_sem": destaque[destaque['Total de contatos'] == 0],

    "padrao_total": padrao_geral,
    "padrao_com": padrao_geral[padrao_geral['Total de contatos'] > 0],
    "padrao_sem": padrao_geral[padrao_geral['Total de contatos'] == 0],

    "padrao_super": padrao_super,
    "padrao_destaque": padrao_destaque,
}

colunas_exibicao = [
    'Código do Imóvel',
    'Tipo do anúncio',
    'Bairro',
    'Cidade',
    'Valor de Venda',
    'Valor do aluguel',
    'Número de fotos',
    'Vídeo',
    'Total de visualizações',
    'Total de contatos',
    'Última atualização',
    'taxa_conversão'
]


def formato_moeda(valor):
    if pd.isna(valor):
        return ""
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


def formato_percentual(valor):
    if pd.isna(valor):
        return ""
    return f"{valor:.2f}%"

if st.session_state.visao in mapa:
    st.subheader("📋 Detalhamento")

    tabela = mapa[st.session_state.visao].copy()

    # mantém somente as colunas desejadas
    tabela = tabela[colunas_exibicao]

    recebeu_contato = tabela['Total de contatos'].sum() > 0

    if recebeu_contato:
        # 🔹 Tabelas que receberam contato
        tabela = tabela.sort_values(by='taxa_conversão', ascending=False)

        st.dataframe(
            tabela.style
            .format({
                'Valor de Venda': formato_moeda,
                'Valor do aluguel': formato_moeda,
                'taxa_conversão': formato_percentual
            })
            .applymap(
                estilo_taxa_conversao,
                subset=['taxa_conversão']
            ),
            use_container_width=True,
            hide_index=True
        )

    else:
        # 🔹 Tabelas que NÃO receberam contato
        tabela = tabela.sort_values(by='Total de visualizações', ascending=False)

        st.dataframe(
            tabela.style
            .format({
                'Valor de Venda': formato_moeda,
                'Valor do aluguel': formato_moeda,
                'taxa_conversão': formato_percentual
            })
            .apply(
                lambda row: [
                    estilo_visualizacoes(row['Total de visualizações'], row['Tipo do anúncio'])
                    if col == 'Total de visualizações' else ""
                    for col in tabela.columns
                ],
                axis=1
            ),
            use_container_width=True,
            hide_index=True
        )